.\" -*- mode: troff; coding: UTF-8 -*-
.TH myconnector 1  "June 10, 2020" "version 2.0" "USER COMMANDS"
.SH NAME
myconnector \- Инструмент системного администратора
.SH SYNOPSIS
.B myconnector
[options]
.SH DESCRIPTION
Программа-агрегатор для осуществления подключения к различным
компьютерным системам по всем распространенным протоколам (RDP, VNC,
Citrix, VMware и прочие).
.SH OPTIONS
.TP
\fBбез\ опций\fR
.RS 3
запуск программы с GUI
.RE
.PP
\fB<имя_подключения>\fR
.RS 3
быстрое соединение c указанным сохраненным подключением
.RE
.PP
\fB<имя_файла>\fR
.RS 3
возможно подключение с помощью файлов .myc, .remmina и .rdp
.RE
.PP
\fB--kiosk\fR
.RS 3
настройка режима Киоск (при наличии доступа и пакета \fImyconnector-kiosk\fR)
.RE
.PP
\fB-h,\ --help\fR
.RS 3
вывести справку
.RE
.PP
\fB-v,\ --version\fR
.RS 3
вывести версию и релиз программы
.RE
.PP
\fB-d,\ --debug\fR
.RS 3
запустить в режиме отладки (отображение логов)
.RE
.PP
\fB-q,\ --quit\fR
.RS 3
принудительно завершить работу имеющейся копии программы
.SH LINKS
http://myconnector.ru/
.SH AUTHOR
Korneechev Evgeniy <ek@myconnector.ru>
