#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Инструмент командной строки для изменения параметров программы Connector
# Источник: https://jenyay.net/Programming/Argparse

import sys
import argparse

version = "0.1"

def createParser ():
    parser = argparse.ArgumentParser()
    parser.add_argument ('file')
    parser.add_argument ('--version')
    return parser

def main():
    parser = createParser()
    namespace = parser.parse_args(sys.argv[1:])
    return 0

if __name__ == '__main__':
    main()

