#!/bin/bash

# Checking avaiable chromium
which chromium > /dev/null 2>&1
if [ "$?" -eq 0 ]; then
    KIOSK_COMMAND="chromium --kiosk --incognito"
else
    KIOSK_COMMAND="firefox --kiosk --private-window"
fi

# Checking avaiable window manager
WM=""
for i in marco /usr/lib/kf5/bin/kwin_x11 openbox awesome; do
    which $i > /dev/null 2>&1
    if [ "$?" -eq 0 ]; then
        WM=$i
        break
    fi
done

