#!/bin/bash

# Checking avaiable chromium
which chromium > /dev/null 2>&1
if [ "$?" -eq 0 ]; then
    KIOSK_COMMAND="chromium --incognito"
else
    KIOSK_COMMAND="firefox --private-window"
fi

# marco - default window manager in MATE.
# You also may be try openbox, awesome and others WM.
marco --replace &

while :
do
$KIOSK_COMMAND --kiosk $1
done
