#!/bin/bash

# MyConnector
# Copyright (C) 2020 Evgeniy Korneechev <ek@myconnector.ru>

# This program is free software; you can redistribute it and/or
# modify it under the terms of the version 2 of the GNU General
# Public License as published by the Free Software Foundation.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program. If not, see http://www.gnu.org/licenses/.

# Checking avaiable chromium
which chromium > /dev/null 2>&1
if [ "$?" -eq 0 ]; then
    KIOSK_COMMAND="chromium --kiosk --incognito"
else
    KIOSK_COMMAND="firefox --kiosk --private-window"
fi

# marco - default window manager in MATE.
# You also may be try openbox, awesome and others WM.
marco --replace &

while :
do
$KIOSK_COMMAND $1
done
