.\" -*- mode: troff; coding: UTF-8 -*-
.TH connector 1  "Jule 25, 2018" "version 1.7.1" "USER COMMANDS"
.SH NAME
connector \- Инструмент системного администратора
.SH SYNOPSIS
.B connector
[<имя подключения>/<файл формата .ctor>]
.SH DESCRIPTION
 Программа-агрегатор для осуществления подключения к различным
 компьютерным системам по всем распространенным протоколам (RDP, VNC,
 Citrix, VMware и прочие).
.PP
 Wiki: http://wiki.myconnector.ru
.SH OPTIONS
.TP
 без опций
 запуск программы с GUI;
.TP
 [<имя подключения>]
 быстрое соединение c указанным сохраненным подключением;
.TP
 [<файл формата .ctor>]
 открытие файла и запуск подключения с сохраненными в нем настройками.
.SH AUTHOR
 Корнеечев Евгений (ek@myconnector.ru)
