.\" -*- mode: troff; coding: UTF-8 -*-
.TH connector 1  "March 31, 2017" "version 1.4.0" "USER COMMANDS"
.SH NAME
connector \- Инструмент системного администратора
.SH SYNOPSIS
.B connector
[<файл подключения>]
.SH DESCRIPTION
Программа-агрегатор для осуществления подключения с различным
компьютерным системам по всем распространенным протоколам (RDP, VNC,
Citrix, VMware и прочие).
.PP
Wiki: http://wiki.myconnector.ru
.SH OPTIONS
.TP
без опций
запуск программы с GUI
.TP
[<имя подключения>]
быстрое соединение c указанным сохраненным подключением
.SH AUTHOR
Корнеечев Евгений (ek@myconnector.ru)
