#!/usr/bin/python3

from sys import path
from os import getcwd, chdir
MAINFOLDER = "/usr/share/connector"
path.append(MAINFOLDER)
pwd = getcwd() + '/'
chdir(MAINFOLDER)
import gui
if __name__ == '__main__':
    gui.f_main(pwd)
