#!/usr/bin/python3
from os import system
from sys import exit

def main():
    system( "zenity --notification --window-icon=connector --text='Программа Connector\n"
            "Данная программы устарела!\nИспользуйте MyConnector!'" )
    exit(0)

if __name__ == "__main__":
    main()
